version: '3.1'
services:
  mongodb:
    image: mongo:6.0
    container_name: joboverboard_mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
